users:
  name_length: 50
  email_length: 255
  pass_min_length: 6
  phone_min: 10
  phone_max: 15
  per_page: 10
conditions:
  checked: "1"
  approved: "on"
products:
  per_page: 12
  hot_page: 8
  fake_sale: 1.5
  max_stars: 5
  round: 2
  name_length: 50
  tmp_type: 1
  review_page: 10
  quantity_min: 1
  default:
    id: 1
    name: "Adidas"
    info: "From New York"
    quantity: 10
    price: 20
    category_id: 1
cart:
  per_page: 3
  size_img: "50x50"
